# Generated by Django 4.2.4 on 2023-08-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('personal_id', models.CharField(max_length=10)),
                ('belt_colour', models.CharField(max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('academy', models.CharField(max_length=50)),
                ('clase', models.CharField(max_length=50)),
            ],
        ),
    ]
