# Generated by Django 4.2.4 on 2023-08-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BJJCrudAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
