# Generated by Django 4.2.4 on 2023-08-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BJJCrudAPP', '0003_alter_student_academy_alter_student_belt_colour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='absoluto',
            field=models.BooleanField(default=False, max_length=50, verbose_name='Absoluto'),
        ),
        migrations.AddField(
            model_name='student',
            name='monto_pago',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='monto_pago'),
        ),
    ]
