# Generated by Django 4.2.4 on 2023-08-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BJJCrudAPP', '0004_student_absoluto_student_monto_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='clase',
            new_name='age_class',
        ),
        migrations.AddField(
            model_name='student',
            name='weight_class',
            field=models.CharField(max_length=50, null=True, verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='student',
            name='belt_colour',
            field=models.CharField(choices=[('blanco', 'Blanco'), ('azul', 'Azul'), ('violeta', 'Violeta'), ('marron', 'Marron'), ('preta', 'Preta')], max_length=20, verbose_name='Faixa'),
        ),
        migrations.AlterField(
            model_name='student',
            name='personal_id',
            field=models.CharField(max_length=40, verbose_name='DNI'),
        ),
    ]
